langsorder:
- id: en

langs:
  en: English

redirects:
  /news: /en/version-history
  /clients: /en/choose-your-wallet
  /about: /en/faq
  /en/bitcoin-for-press: /en/press
  /en/about: /en/faq
  /en/bitcoin-for-enthusiasts: /en/innovation

aliases:
  s_nakamoto: Satoshi Nakamoto
  --author=Satoshi Nakamoto: Satoshi Nakamoto
  gavinandresen: Gavin Andresen
  tcatm: Nils Schneider

safe:        false
port: 4000
base-url:    /

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    kramdown
permalink:   date

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..6
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
